#db.motor=MYSQL
db.motor=POSTGRES

db.postgres.url=jdbc:postgresql://localhost:5434/isw2_postgres
db.postgres.user=postgres
db.postgres.password=clave123

db.mysql.url=jdbc:mysql://localhost:3307/isw2_mysql?useUnicode=true&characterEncoding=UTF-8
db.mysql.user=root
db.mysql.password=clave123
